### Get Properties
GET http://localhost:3000/properties

### Get Featured Properties
GET http://localhost:3000/properties/featured

### Create New Property
POST http://localhost:3000/properties
Content-Type: application/json

{
    "name": "New Property",
    "description": "New Property Description",
    "area": 1000
}

### Get Property By ID
GET http://localhost:3000/properties/1

### Update Property By ID
PATCH  http://localhost:3000/properties/1
Content-Type: application/json

{
    "name": "Updated Property",
    "description": "Updated Property Description",
    "area": 2000
}

### Get Property Owners
GET http://localhost:3000/properties/1/owners?sort=true

### Delete Property By ID
DELETE http://localhost:3000/properties/1