### Get Users
GET http://localhost:3000/users?limit=10

### Create New User
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "New",
    "lastName": "User",
    "email": "newuser1@gmail.com",
    "avatarUrl": "https://www.example.com/avatar.jpg",
    "password": "password"
}

### Get Profile
GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3NDIyMjc3MDUsImV4cCI6MTc0MjMxNDEwNX0.ah1r43wp3SJUKa2rMQCOAOFwtpRHyy_rVYUEMI_di50
    