### Get Users
GET http://localhost:3000/users?limit=10

### Create New User
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "New",
    "lastName": "User",
    "email": "newuser1@gmail.com",
    "avatarUrl": "https://www.example.com/avatar.jpg",
    "password": "password"
}

### Get Profile
GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3NDMwNTk3OTQsImV4cCI6MTc0MzA2MzM5NH0.PJzNZ_-R3mqAzJhRDSs4eEVQCjWVp5PZpqG2gC67mrw

### Remove User
DELETE http://localhost:3000/users/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3NDMwNTk3OTQsImV4cCI6MTc0MzA2MzM5NH0.PJzNZ_-R3mqAzJhRDSs4eEVQCjWVp5PZpqG2gC67mrw