### Get Users
GET http://localhost:3000/users?limit=10

### Create New User
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "New",
    "lastName": "User",
    "email": "newuser1@gmail.com",
    "avatarUrl": "https://www.example.com/avatar.jpg",
    "password": "password"
}

### Get Profile
GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJpYXQiOjE3NDI5Njk5ODUsImV4cCI6MTc0Mjk3MzU4NX0.LOxVodDbZVznzyFTOu4dkyTEeN_S3wVQBy_odTGrFro